# Generated by Django 5.0.6 on 2024-06-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='messages',
            field=models.ManyToManyField(blank=True, to='chat.messages'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='chat.chats'),
        ),
    ]
